// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MESSAGE_MESSAGES_H_
#define FLATBUFFERS_GENERATED_MESSAGE_MESSAGES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace messages {

struct Controller;
struct ControllerBuilder;

struct Controller FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ControllerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LEFT_STICK_X = 4,
    VT_LEFT_STICK_Y = 6,
    VT_RIGHT_STICK_X = 8,
    VT_RIGHT_STICK_Y = 10
  };
  float left_stick_x() const {
    return GetField<float>(VT_LEFT_STICK_X, 0.0f);
  }
  float left_stick_y() const {
    return GetField<float>(VT_LEFT_STICK_Y, 0.0f);
  }
  float right_stick_x() const {
    return GetField<float>(VT_RIGHT_STICK_X, 0.0f);
  }
  float right_stick_y() const {
    return GetField<float>(VT_RIGHT_STICK_Y, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_LEFT_STICK_X, 4) &&
           VerifyField<float>(verifier, VT_LEFT_STICK_Y, 4) &&
           VerifyField<float>(verifier, VT_RIGHT_STICK_X, 4) &&
           VerifyField<float>(verifier, VT_RIGHT_STICK_Y, 4) &&
           verifier.EndTable();
  }
};

struct ControllerBuilder {
  typedef Controller Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_left_stick_x(float left_stick_x) {
    fbb_.AddElement<float>(Controller::VT_LEFT_STICK_X, left_stick_x, 0.0f);
  }
  void add_left_stick_y(float left_stick_y) {
    fbb_.AddElement<float>(Controller::VT_LEFT_STICK_Y, left_stick_y, 0.0f);
  }
  void add_right_stick_x(float right_stick_x) {
    fbb_.AddElement<float>(Controller::VT_RIGHT_STICK_X, right_stick_x, 0.0f);
  }
  void add_right_stick_y(float right_stick_y) {
    fbb_.AddElement<float>(Controller::VT_RIGHT_STICK_Y, right_stick_y, 0.0f);
  }
  explicit ControllerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Controller> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Controller>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Controller> CreateController(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float left_stick_x = 0.0f,
    float left_stick_y = 0.0f,
    float right_stick_x = 0.0f,
    float right_stick_y = 0.0f) {
  ControllerBuilder builder_(_fbb);
  builder_.add_right_stick_y(right_stick_y);
  builder_.add_right_stick_x(right_stick_x);
  builder_.add_left_stick_y(left_stick_y);
  builder_.add_left_stick_x(left_stick_x);
  return builder_.Finish();
}

inline const messages::Controller *GetController(const void *buf) {
  return ::flatbuffers::GetRoot<messages::Controller>(buf);
}

inline const messages::Controller *GetSizePrefixedController(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<messages::Controller>(buf);
}

inline bool VerifyControllerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<messages::Controller>(nullptr);
}

inline bool VerifySizePrefixedControllerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<messages::Controller>(nullptr);
}

inline void FinishControllerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<messages::Controller> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedControllerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<messages::Controller> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace messages

#endif  // FLATBUFFERS_GENERATED_MESSAGE_MESSAGES_H_
