// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MESSAGE_MESSAGES_H_
#define FLATBUFFERS_GENERATED_MESSAGE_MESSAGES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace messages {

struct Command;
struct CommandBuilder;

struct Command FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CommandBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ODOM = 4,
    VT_MOTOR = 6
  };
  int32_t odom() const {
    return GetField<int32_t>(VT_ODOM, 0);
  }
  int32_t motor() const {
    return GetField<int32_t>(VT_MOTOR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ODOM, 4) &&
           VerifyField<int32_t>(verifier, VT_MOTOR, 4) &&
           verifier.EndTable();
  }
};

struct CommandBuilder {
  typedef Command Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_odom(int32_t odom) {
    fbb_.AddElement<int32_t>(Command::VT_ODOM, odom, 0);
  }
  void add_motor(int32_t motor) {
    fbb_.AddElement<int32_t>(Command::VT_MOTOR, motor, 0);
  }
  explicit CommandBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Command> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Command>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Command> CreateCommand(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t odom = 0,
    int32_t motor = 0) {
  CommandBuilder builder_(_fbb);
  builder_.add_motor(motor);
  builder_.add_odom(odom);
  return builder_.Finish();
}

inline const messages::Command *GetCommand(const void *buf) {
  return ::flatbuffers::GetRoot<messages::Command>(buf);
}

inline const messages::Command *GetSizePrefixedCommand(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<messages::Command>(buf);
}

inline bool VerifyCommandBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<messages::Command>(nullptr);
}

inline bool VerifySizePrefixedCommandBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<messages::Command>(nullptr);
}

inline void FinishCommandBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<messages::Command> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedCommandBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<messages::Command> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace messages

#endif  // FLATBUFFERS_GENERATED_MESSAGE_MESSAGES_H_
