// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RESPONSE_MESSAGES_H_
#define FLATBUFFERS_GENERATED_RESPONSE_MESSAGES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace messages {

struct Voltages;
struct VoltagesBuilder;

struct Response;
struct ResponseBuilder;

struct Voltages FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VoltagesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_V = 4
  };
  const ::flatbuffers::Vector<int32_t> *v() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_V);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_V) &&
           verifier.VerifyVector(v()) &&
           verifier.EndTable();
  }
};

struct VoltagesBuilder {
  typedef Voltages Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_v(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> v) {
    fbb_.AddOffset(Voltages::VT_V, v);
  }
  explicit VoltagesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Voltages> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Voltages>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Voltages> CreateVoltages(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> v = 0) {
  VoltagesBuilder builder_(_fbb);
  builder_.add_v(v);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Voltages> CreateVoltagesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int32_t> *v = nullptr) {
  auto v__ = v ? _fbb.CreateVector<int32_t>(*v) : 0;
  return messages::CreateVoltages(
      _fbb,
      v__);
}

struct Response FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VOLTAGES = 4
  };
  const messages::Voltages *voltages() const {
    return GetPointer<const messages::Voltages *>(VT_VOLTAGES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VOLTAGES) &&
           verifier.VerifyTable(voltages()) &&
           verifier.EndTable();
  }
};

struct ResponseBuilder {
  typedef Response Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_voltages(::flatbuffers::Offset<messages::Voltages> voltages) {
    fbb_.AddOffset(Response::VT_VOLTAGES, voltages);
  }
  explicit ResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Response> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Response>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Response> CreateResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<messages::Voltages> voltages = 0) {
  ResponseBuilder builder_(_fbb);
  builder_.add_voltages(voltages);
  return builder_.Finish();
}

inline const messages::Response *GetResponse(const void *buf) {
  return ::flatbuffers::GetRoot<messages::Response>(buf);
}

inline const messages::Response *GetSizePrefixedResponse(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<messages::Response>(buf);
}

inline bool VerifyResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<messages::Response>(nullptr);
}

inline bool VerifySizePrefixedResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<messages::Response>(nullptr);
}

inline void FinishResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<messages::Response> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<messages::Response> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace messages

#endif  // FLATBUFFERS_GENERATED_RESPONSE_MESSAGES_H_
